// Package container implements Nodexa Agent's local container management
// foundation. Phase 1 is deliberately minimal: it drives the OCI reference
// runtime `runc` directly rather than a full container daemon (containerd,
// Docker), keeping the OS lightweight and the dependency surface small.
// Docker Compose-style multi-container deployments are a future Nodexa
// Deploy concern layered on top of this foundation.
//
// Each container is an "OCI bundle" directory under the container data
// directory (/var/lib/nodexa/containers/<name>/), containing:
//
//	config.json    OCI runtime spec (generated by nodexa-agent)
//	rootfs/        the container's root filesystem
//	metadata.json  Nodexa-specific bookkeeping (image label, timestamps)
package container

import "time"

// State is a container's lifecycle state as tracked by Nodexa Agent. It is
// a small, Nodexa-native vocabulary layered over runc's own state machine.
type State string

const (
	StatePullingImage     State = "pulling image"
	StateInstallingImage  State = "installing image"
	StateContainerCreated State = "container created"
	StateCreated          State = "created"
	StateRunning          State = "running"
	StateStopped          State = "stopped"
	StateFailed           State = "failed"
)

// Container describes one locally managed container.
type NodexaContainer struct {
	Name      string    `json:"name"`
	Image     string    `json:"image"`
	Command   []string  `json:"command"`
	State     State     `json:"state"`
	PID       int       `json:"pid,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	StartedAt time.Time `json:"started_at,omitempty"`
	// DeploymentName/DeploymentRevision identify the Nodexa Deploy
	// deployment (internal/deploy) that owns this container, if any -- both
	// are empty/zero for seeded or manually started containers.
	DeploymentName     string `json:"deployment_name,omitempty"`
	DeploymentRevision int    `json:"deployment_revision,omitempty"`
	Network            string          `json:"network,omitempty"`
	IPAddress          string          `json:"ip_address,omitempty"`
	Ports              []ContainerPort `json:"ports,omitempty"`
	Aliases            []string        `json:"aliases,omitempty"`
}

// ServiceSpec is one compose-style service from a Nodexa Deploy deployment
// -- one container, one OCI bundle on the device. Field shapes and JSON
// tags mirror nodexa-backend's app/models/deployment.py::ServiceSpec
// exactly, since internal/backend.DeploymentResponse decodes directly into
// this type rather than a separate wire-format mirror.
type ServiceSpec struct {
	Name          string            `json:"name"`
	Image         string            `json:"image"`
	ContainerName string            `json:"container_name,omitempty"`
	Command       []string          `json:"command,omitempty"`
	Env           map[string]string `json:"env,omitempty"`
	Ports         []ContainerPort   `json:"ports,omitempty"`
	Mounts        []ContainerMount  `json:"mounts,omitempty"`
	Volumes       []ContainerVolume `json:"volumes,omitempty"`
	// "host" (default): no network namespace, same as today's seeded
	// bundles. "bridge": a per-container network namespace + CNI, not yet
	// implemented (see the Nodexa Deploy plan's phase 3c).
	Network string `json:"network"`
	// "no" (default), "always", "unless-stopped" or "on-failure": whether
	// Supervise restarts the container after its process exits.
	Restart string `json:"restart"`
}

// ContainerPort is one published port. Only meaningful once "bridge"
// networking is implemented -- "host" services already expose every port
// they bind directly, with nothing for Nodexa Agent to publish.
type ContainerPort struct {
	ContainerPort int    `json:"container_port"`
	HostPort      int    `json:"host_port"`
	Protocol      string `json:"protocol"`
}

// ContainerMount is a bind mount from the host filesystem into the
// container.
type ContainerMount struct {
	HostPath      string `json:"host_path"`
	ContainerPath string `json:"container_path"`
	ReadOnly      bool   `json:"read_only"`
}

// ContainerVolume is a Nodexa-managed local volume: nodexa-agent creates
// and bind-mounts a directory under the manager's volumes dir for this --
// there is no shared/distributed volume driver (see docs/handoff.md's
// "foundation not full engine" scoping for the rest of the runtime).
type ContainerVolume struct {
	Name          string `json:"name"`
	ContainerPath string `json:"container_path"`
}

// RegistryCredential is the pull credential for one image registry, as
// delivered by nodexa-backend's device-facing deployment endpoint. A nil
// *RegistryCredential passed to Deploy means an anonymous/public pull.
type RegistryCredential struct {
	Registry string `json:"registry"`
	Username string `json:"username"`
	Token    string `json:"token"`
}

// NodexaContainerStats is a point-in-time resource usage sample for a
// running container, read from its cgroup.
type NodexaContainerStats struct {
	Name             string    `json:"name"`
	CPUUsageSeconds  float64   `json:"cpu_usage_seconds"`
	MemoryUsageBytes uint64    `json:"memory_usage_bytes"`
	MemoryLimitBytes uint64    `json:"memory_limit_bytes,omitempty"`
	PIDs             int       `json:"pids"`
	Timestamp        time.Time `json:"timestamp"`
}

// metadata is the Nodexa-specific record persisted alongside each OCI
// bundle, since runc itself only tracks bundles it currently considers
// active (it forgets a container's existence once deleted from its own
// state, but Nodexa still wants to remember "stopped" containers).
type metadata struct {
	Name      string    `json:"name"`
	Image     string    `json:"image"`
	Command   []string  `json:"command"`
	CreatedAt time.Time `json:"created_at"`
	StartedAt time.Time `json:"started_at,omitempty"`
	// CgroupPath is the cgroup v2 path (relative to /sys/fs/cgroup) runc
	// was configured to place this container under, used later to read
	// stats without depending on runc's own (transient) process tracking.
	CgroupPath string `json:"cgroup_path"`
	// DeploymentName/DeploymentRevision tag bundles created by Nodexa
	// Deploy's poll/apply loop (internal/deploy), so Apply can tell its own
	// managed containers apart from seeded/manually started ones when
	// diffing a new deployment spec against what's currently running.
	// Empty/zero for non-Deploy-managed bundles.
	DeploymentName     string `json:"deployment_name,omitempty"`
	DeploymentRevision int    `json:"deployment_revision,omitempty"`
	Network            string          `json:"network,omitempty"`
	IPAddress          string          `json:"ip_address,omitempty"`
	Ports              []ContainerPort `json:"ports,omitempty"`
	Aliases            []string        `json:"aliases,omitempty"`
	// Restart is the service's compose restart policy (see restart.go).
	Restart string `json:"restart,omitempty"`
}
